### ISSUE TITLE
Refresh token issue

### ISSUE THREAD

**Issue by joshua-kissinger** [TSheetsTeam/api_dotnet#1]
This has been a really helpful starter library (thank you) and I'd fix this myself, but it's at the point where I'm most confused by what is actually happening under the covers with oath/refresh tokens, but I presume _token = null, followed by _token.refresh_token, is a problem, right? 

```
public OAuthToken GetToken()
        {
            if (_token == null)
            {
                return Authenticate();
            }
            else if (_token.NeedsRefresh())
            {
                _token = null;
                try
                {
                    _token = RestClient.RefreshToken(_token.refresh_token, _connectionInfo);
                }
                //..
            }
          //..
         }
```

**Comment by scottjeide** [comment]
Yes, you're absolutely correct! Thanks for catching that.

The intent of that was to null out the token in case the RefreshToken call failed so we didn't hold onto an invalid token afterwards and attempt to use it, but as it's written that'll just break the refresh anyway.

I'm thinking it'd probably be better to grab a copy of the refresh token before nulling out the OAuthToken object and then use the copy in the refresh call.

You're more than welcome to submit a PR with the fix and I'll merge it in so you can get the github credit for the issue and subsequent fix. Or if you'd rather not then I can make the change.

Thank you again for pointing that out!

**Comment by joshua-kissinger** [comment]
I'd be happy to give it a shot, though I've done one or two PRs, so if I get it wrong, feel free to do whatever makes sense to fix it. 

I will say, I tried fixing it in my own code, and I always got a 400 error (if I'm recalling correctly) when I tried to call the "grant" endpoint (via public static OAuthToken RefreshToken) with a recently created, non-revoked, refresh token. It's certainly possible I'm doing something wrong, but I reviewed your code and my and didn't see anything wrong with how the request was formed. 

---
Mostly unrelated question, but if it's not a difficult/time consuming answer, I'd certainly appreciate any guidance:  I'm trying to store the token in our database for re-use, but despite your helpful comments in the code about saving / updating the tokens, I'm struggling to see exactly where to best hook-in. In my mind, it's as "simple" as... 
1. Check if you have any stored token before you utilize the "AuthenticateWithBrowser".
2. If you don't have a stored token, authenticate with the browser and store the resulting token.
3. If you have a stored token, call the getToken process that checks if it needs to be refreshed.
4. If it needs to be refreshed, call the grant/refresh endpoint and store the updated token.
5. If the refresh process fails, clear the stored token and somehow message the user to try again, which will trigger the browser-based authentication.

Am I misunderstanding / overlooking anything big?

**Comment by scottjeide** [comment]
For storing the token, one hopefully simple approach is you could register your own callback for the TokenChanged event. That event should fire every time you get a new token (see line 152 of the TSheetsApiSamples.Program.cs). In this callback you could can the ToJson method on the returned token to get a string that can be written out to your database or stored as an encrypted value in the registry or something. It is essentially a password, so you'll want to treat it securely. 

At program startup or whenever you need to create an OAuthToken object, just read that saved value. If you have one, call the FromJson method on the OAuthToken class to re-hydrate the token object with the saved data and use it. If you don't have a saved one, just use an empty OAuthToken object and of course if you get a changed event on it, the persist that data.

**Comment by scottjeide** [comment]
For testing the refresh behavior and subsequent token changed event, a relatively simple way to force it to refresh early is to change NeedsRefresh() line 563 to just set it to 1 second in the future (or just pause there in the debugger and change the value). That will force it to automatically refresh the token much sooner than necessary, but is a simpler way than waiting a week! 

Of course that'll only work with the previous fix you mentioned. Here's what I just hacked in to test it.
`            else if (_token.NeedsRefresh())
            {
                var refreshToken = _token.refresh_token;
                _token = null;
                try
                {
                    _token = RestClient.RefreshToken(refreshToken, _connectionInfo);
                }
                catch (ApiException ex)
                {
                    if (ex.HttpCode != "404")
                    {
                        // unexpected refresh error
                        throw;
                    }
                    // else the server didn't like the refresh token so it's now invalid
                }
                
                OnTokenChanged(_token);
                return _token;
            }
`

**Comment by scottjeide** [comment]
I'm having trouble with the formatting on that, but hopefully it makes sense

**Comment by joshua-kissinger** [comment]
Yeah, it makes sense. I was just setting it to true and tracing through, but I kept getting an error from tsheets. I'll test fresh again tomorrow and see if it was something with the token.  Thanks for your help. Hopefully I did the pull request right! The code was easy enough, but I haven't done all that many pull requests, and none on github.  Thanks again!

**Comment by scottjeide** [comment]
This one is fixed now. Thanks @secorguy !
