### ISSUE TITLE
Refresh token flow

### ISSUE THREAD

**Issue by joshua-kissinger** [TSheetsTeam/api_dotnet#3]
I think, but am not expert enough to be sure, that there is a problem with the refresh request flow. I can refresh a token using curl, but it fails when using this library. I'm not sure of the "right" way, but in TSheets example, they show that they are setting an Authorization header when requesting a refresh token. Their [example](https://developers.tsheets.com/docs/api/authentication):

`curl -i -X POST -H "Authorization: Bearer 84ec7a2f2b1379990caea347d67e713f34f2d5dz" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=refresh_token" -d "client_id=MYAPPCLIENTID" -d "client_secret=MYAPPSECRET" -d "refresh_token=0ed645dbcfaca681e37df26df6f39d273330e7a0" "https://rest.tsheets.com/api/v1/grant"`

In this library's code, the refresh flow is using "SendRequest" not "SendAuthenticatedRequest" to request a refresh token. When I added an Authorization header in "RefreshToken", before calling "SendRequest," everything worked. Since I thought at least part of the idea behind a refresh token was that it could be used even after an access token has expired to get a new access token, I tried, in separate requests, sending both the access token and the refresh token, in the Authorization header - both worked, but the access token wasn't actually expired, so I don't know if it would always work or not.

Any thoughts if I'm onto something here, or if you think I'm doing something else wrong that is causing my refresh issue?

**Comment by scottjeide** [comment]
Thanks for the fix @dustinsweet !

**Comment by joshua-kissinger** [comment]
Thank you both!

**Comment by dustinsweet** [comment]
And thank you for letting us know!
