### ISSUE TITLE
TSheets Types

### ISSUE THREAD

**Issue by Psypher9** [TSheetsTeam/api_dotnet#5]
Hello,

I'm just curious if you guys would be open to a PR to include classes that allow for the API's return values to be strongly typed. I can see that including a standard library of classes could be very beneficial.

From what I've looked at of the code, I have an idea to add a strongly typed layer over the main RestClient. I'm a contributor for RestSharp as well and I'm pretty familiar with it.

**Comment by dustinsweet** [comment]
Hi Turner, strong typing will be coming soon for the TSheet .NET API client.  We'll be starting development in an upcoming sprint.  Thanks for reaching out!

**Comment by Psypher9** [comment]
Fantastic!
