### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by Psypher9** [TSheetsTeam/api_dotnet#6]
Would you all be open to a PR to bring this SDK up to the .NET Standard, in order to support both the .NET Framework and .NET Core? I'd even be willing to make sure we can maintain build directives for .NET 4.5 if you are concerned about backwards compatibility.

**Comment by dustinsweet** [comment]
Hi Turner,

We have plans for a completely separate .NET Standard version of the SDK, but it's a ways off on the roadmap.   If you'd like to get a head start, feel free to fork our Framework version.  Please be aware we'll have some upcoming changes to introduce strong object types and schemas to our existing SDK, and there will likely be some refactoring of existing code.  To limit rework, it would make the most sense to wait until these changes are in.  Thanks for reaching out, glad to have your help!

**Comment by tsheets** [comment]
Is creating a .NET SDK something someone might work on in personal dev (me?) ?


David Hardy
Software Developer
[cid:image001.png@01D3A66E.15A8BE30]<http://tsheets.com/>

Intuit | Powering prosperity around the worldtm

**Comment by dustinsweet** [comment]
Our new .NET Standard Full SDK is now available, here: https://github.com/intuit/TSheets-V1-DotNET-SDK
